### PR TITLE
readId() fails, when timeStamp is appended to JSession

### PR DESCRIPTION
**Pull request by sd1248**
Fixed the jsession readId issue when timestamp is suffixed.

### CODE REVIEW

**Comment by nbogojevic** [comment]
This pull request addresses: #11

**Comment by nbogojevic** [comment]
Thanks for the pull request, I'd rather we do the fix in BaseSessionTracking in clean method. ATM notion of timestamp is handled there, and I want to keep it in single place.

**Comment by mgarcez** [comment]
Thanks for the changes.
Could you please also add unit tests?

**Comment by nbogojevic** [comment]
In addition to unit tests, please add masking based on appendTimestamp in clean method before merging.

**Comment by sd1248** [comment]
I am not sure what check is failing. In my local, the build is successful. When I click on the failure details, it says, secure connection failed and a blank page appears. If any of the contributors have have to it, pl let me know what is failing. I will check and fix.

**Comment by nbogojevic** [comment]
@sd1248 when I said 

> masking based on appendTimestamp

I was meaning "entering the timestamp parsing code only when appendTimestamp is set tu `true`". You shouldn't have done refactoring with extraction of Base64 handler here. Can you go back to old code with only addition being the test to check if appendTimes (see comment in BaseSessionTracking).

**Pull request merged**
